### ISSUE TITLE
Missing release 1.2.34

### ISSUE THREAD

**Issue by prston** [pfpayments/prestashop-1.7#10]
Hello,

V1.2.34 has been released but the module .zip file is missing.
Thank you.

Alex

**Comment by theodorspringwallee** [comment]
Dear [prston](https://github.com/prston)

You can always download the .zip of the newest release here:
![image](https://user-images.githubusercontent.com/85299706/211275077-550439ad-b36a-441f-a85d-b061dcb0a950.png)

Please, can you precise what exactly you are missing?

Best regards

**Comment by prston** [comment]
> Dear [prston](https://github.com/prston)
> 
> You can always download the .zip of the newest release here: ![image](https://user-images.githubusercontent.com/85299706/211275077-550439ad-b36a-441f-a85d-b061dcb0a950.png)
> 
> Please, can you precise what exactly you are missing?
> 
> Best regards

@theodorspringwallee  Looks like there is a problem with the module then.....
![Screenshot from 2023-01-09 11-34-47](https://user-images.githubusercontent.com/2537365/211289044-871bf143-c864-48b8-9e67-8fc2f23115f6.png)

**Comment by theodorspringwallee** [comment]
Dear [prston](https://github.com/prston)

Please, can you check the following workaround.

1. Unzip the zip file.
2. Rename the contained folder into "postfinancecheckout"
3. Zip this folder again and upload the new zip

Thank you for trying this.

Best regards

**Comment by prston** [comment]
@theodorspringwallee yep it is working, well noted on my side. BTW that's why I was mentionning a "missing release file", accordingly to the previous releases the "ready to use" zip file was available as an asset.

Thank you!
