### ISSUE TITLE
Compatible with PrestaShop 8 and PHP-8

### ISSUE THREAD

**Issue by Hasan-Shaker** [pfpayments/prestashop-1.7#11]
When i install pfpayments in PS 8 with PHP-8 i have this Error.
![Capture d’écran du 2023-02-27 14-03-21](https://user-images.githubusercontent.com/51764849/221570918-df5b26fd-8c24-4c61-ad8c-4e3968ee770d.png)

do I need to do anything or are you doing an update ?

**Comment by theodorspringwallee** [comment]
Dear [Hasan-Shaker](https://github.com/Hasan-Shaker)

Currently, we don't provide the PFC solution for PrestaShop 8, but we have this in planning.

When we are done, we will deploy the PS 8/PFC plugin on a separate repository, which you can find then on https://github.com/pfpayments (search there for Prestashop-8). 

In the meanwhile, we recommend to still use the PS 1.7 to be compatible with our plugin.

Best regards
