### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by peterpeter** [pfpayments/prestashop-1.7#12]
Hi
It's about release 1.2.34
According to the description at Postfinance 
https://plugin-documentation.postfinance-checkout.ch/pfpayments/prestashop-1.7/master/docs/en/documentation.html
I downloaded the zip-package and tried to install it. But that didn't work, I got an 'Invalid Zip Format' error:
![image](https://user-images.githubusercontent.com/485313/228443011-d8a04a19-ffd7-4aca-88b7-481d8386cd76.png)

Then I unzipped and uploaded the module via FTP and tried to install it via the module manager. Then I got the following error:
![image](https://user-images.githubusercontent.com/485313/228442788-a580c1ac-0283-402a-b01e-286dc3a06393.png)

So how can I install the plugin?
Thanks
Roger

**Comment by theodorspringwallee** [comment]
Dear [peterpeter](https://github.com/peterpeter)

Please, can you check the following workaround.

1. Unzip the downloaded zip file.
2. Rename the contained folder into "postfinancecheckout"
3. Zip this folder again and upload the new zip

Thank you for trying this.

Best regards

**Comment by peterpeter** [comment]
Hi @theodorspringwallee 
The package contains two modules: postfinancecheckout and wallee. Do I need only the postfinancecheckout module in order to get this to work, is that correct?
(the client has a valid pf-checkout account)

I tried your suggestion and I get the same error:
![image](https://user-images.githubusercontent.com/485313/228468409-eb662a49-2813-44fe-83fa-10fe59ae9093.png)

**Comment by peterpeter** [comment]
See attached the used archive.
[postfinancecheckout.zip](https://github.com/pfpayments/prestashop-1.7/files/11098018/postfinancecheckout.zip)

**Comment by peterpeter** [comment]
It worked with success!

With the complete folder in the archive, as you correctly stated (not just the files and folders).

Thank you
Roger
