### ISSUE TITLE
No invoice attached to the mail

### ISSUE THREAD

**Issue by peterpeter** [pfpayments/prestashop-1.7#14]
Freshly installed Version 1.2.39 in a PS 1.7.8.9

With activated checkout module on a order with payment bankwire no invoice is attached to the 'bankwire'-mail. 
With checkout module deactivated the invoice is attached to the mail again - as it should.

**Comment by theodorspringwallee** [comment]
Dear [peterpeter](https://github.com/peterpeter)

Please consider, that the PFC plugin is only compatible with the standard environment of PrestaShop.

As I see, the "bankwire" payment method is not part of the standard environment.

If you want us to create compatibility for this, feel free to contact the PF support (https://www.postfinance.ch/de/support/hotline.html), that they can check a possible feature request.

Best regards

**Comment by peterpeter** [comment]
I mean the payment module ps_wirepayment, which is delivered with every new Prestashop, so it is very much a standard environment.

**Comment by theodorspringwallee** [comment]
Dear [peterpeter](https://github.com/peterpeter)

From what we see, the module is developed by PrestaShop but not installed by default:
![grafik](https://github.com/pfpayments/prestashop-1.7/assets/85299706/89657a4d-a6b3-4321-970d-e6c56e12667f)

Therefore, please can you contact the PF support (https://www.postfinance.ch/de/support/hotline.html), than they can decide with the management, if there will be a feature request for the compatibility with this.

Best regards
