### ISSUE TITLE
There was a technical issue, please try again.

### ISSUE THREAD

**Issue by carlinadesax** [pfpayments/prestashop-1.7#4]
There seems to be a problem with the module. On Prestahop 1.7.7.2 the module does not work. When trying to pay with any payment method, the site displays this error: There was a technical issue, please try again.

**Comment by theodorspringwallee** [comment]
Dear [carlinadesax](https://github.com/carlinadesax)

Sorry for the late response. 

If it still should be an issue please conact: info@wallee.com
