### ISSUE TITLE
Exception stored in Prestashop logs on 1.2.20

### ISSUE THREAD

**Issue by prston** [pfpayments/prestashop-1.7#5]
Hello,

Since a few days, there is some errors logs (backoffice logs) in my PS 1.7.8.3 using the module version 1.2.20.

_Exception on hook paymentOptions for module . Plugin tag \'postfinancecheckout_clean_html\' already registered_ 

How can I help to debug that ?
Thank you.

**Comment by prston** [comment]
Up ?

**Comment by prston** [comment]
Is there someone behind this repository ?

**Comment by theodorspringwallee** [comment]
Dear [prston](https://github.com/prston)

Sorry for the late response. If this issue is still important for you please contact PostFinance directly: https://www.postfinance.ch/en/support/hotline.html
