### ISSUE TITLE
Payment Option on Invoice is "Postfinance Checkout"

### ISSUE THREAD

**Issue by oliiix** [pfpayments/prestashop-1.7#8]
In Prestashop 1.6 our invoices displayed the actual payment option of the module and not just the module's name. Would be great if that could be arranged again for Prestashop 1.7. Since I switched to Prestashop 1.7 the payment method on the invoices is always just "Postfinance Checkout" instead of Twint, Paypal, Postfinance, Card, etc. Would that be possible to get the real payment method on the invoices back? I checked overrides and templates, they all seem to be ok on my end.

Thanks a lot for consideration :)

**Comment by theodorspringwallee** [comment]
Dear [oliiix](https://github.com/oliiix)

On our Prestashop 1.7 test system (in a standard environment), the specific payment method is still on the invoice.
![Bildschirm­foto 2023-01-05 um 16 11 01](https://user-images.githubusercontent.com/85299706/210813281-b9363db1-b02b-45d4-81d9-0d2e88fc7846.png)

If you want, that we do further investigations in our case, please create a ticket by contacting info@wallee.com

Best regards
